### ISSUE TITLE
Ripple effect inconsistency when switching tabs with keyboard

### ISSUE THREAD

**Issue by halgorithm** [silvestreh/atom-material-ui#125]
If you open a tab and switch back and forth to it using the keyboard, the ripple effect doesn't happen. However, if you click on the tab at least once to cause the ripple, switching with the keyboard will then cause the ripple to happen. This eventually causes some tabs to ripple and others not to when keyboard switching, depending on which ones were clicked on.

Also, I saw that in #114 you mentioned that the ripple isn't supposed to ever happen with keyboard switching... but personally, I'd still like if it did. :P

**Comment by silvestreh** [comment]
@halgorithm yes, this is because a `span` element is appended on click. The span element is the ink. So, if you *never* clicked the tab before, you won't see the ripple.

It's a known issue :smile:

**Comment by silvestreh** [comment]
Fixed on 1.0.0 (ripple only happens on click, not while changing tabs with keyboard shortcuts)

**Comment by halgorithm** [comment]
This is still happening for me with atom-material-ui 1.0.5. Seems like switching tabs with the keyboard now always triggers the ripple effect on the first tab. When switching to the second tab, a faint ripple is also slightly visible on the left side of the second tab (I assume since the animation is overflowing from the first tab).

**Comment by silvestreh** [comment]
I reverted to 0.8.0 … 1.0.x is no longer in the Atom package repository. Releases and tags are also gone. The only remaining of 1.0.x are upset users and a bunch of issues :grin: haha 

I still need testers. If you're willing to help, clone this repo and link it using apm. There are instructions in #131.
